---
title: "Input Functions for Text and Passwords"
output: html_document
runtime: shiny
---

# Use `textInput()` for a simple Text Field

## Example

```{r text-input}
textInput(inputId="text1", label="Space to enter text:")
```



## Print the value for `text1`

Either in **console style** using `renderPrint()`:

```{r print-text-input}
renderPrint(input$text1)
```

Or in the same style as surrounding text using `renderText()`:

```{r print-text-input2}
renderText(input$text1)
```


# Use `textAreaInput()` for a Text Area

## Example:

```{r text-area-input}
textAreaInput(inputId="textArea1", label="Area to enter more text:")
```



## Print the value for `textArea1`

```{r print-text-area-input, echo=FALSE}
renderPrint(input$textArea1)
```



# Use `passwordInput()` to hide a Password while typeing

## Example:

```{r password-input}
passwordInput(inputId="password1", label="Protext your password:")
```


## Print the value for `password1`

```{r print-password-input, echo=FALSE}
renderPrint(input$password1)
```


