---
title: "Simple Shiny Document"
author: "Stefan Schmidt"
output: html_document
runtime: shiny
---

# Select input

```{r select-input, echo=FALSE}
selectInput(
  inputId = 'ExampleDropDown',
  label = "Please make a selection",
  choices = list('Value 1' = 1,
                 'Value 2' = 2,
                 'Value 3' = 3)
)
```

Print the value:

```{r print-select-input, echo=FALSE}
renderPrint(input$ExampleDropDown)
```



# Slider Input

```{r slider-input, echo=FALSE}
sliderInput(inputId="sliderExample",
            label="This is a slider",
            min=0,
            max=5,
            value=3
)


sliderInput(inputId="sliderExample2",
            label="Two-ended slider",
            min=0,
            max=10,
            value=c(4, 6)
)

```

# Checkbox Input

```{r checkbox-input, echo=FALSE}
checkboxInput(inputId="checkExample",
              label="Single check box"
)

checkboxGroupInput(inputId="checkGroupExample",
                   label="Multiple check boxes",
                   choices=list("A", "B", "C")
)
```


Checkbox group values:

```{r print-checkboxgroup-input, echo=FALSE}
renderPrint(input$checkGroupExample)
```

# Radio buttons

```{r radio-buttons, echo=FALSE}
radioButtons(inputId="radioSample",
              label="Please choose one",
              choices=list("A", "B", "C")
)
```



Radio button value:

```{r print-radio-input, echo=FALSE}
renderPrint(input$radioSample)
```


# Date Input

```{r date-input, echo=FALSE}
dateInput(inputId="dateChoice",
          label="Date Selector"
)
```


Date value:

```{r print-date-input, echo=FALSE}
renderPrint(input$dateChoice)
```


```{r dates-input, echo=FALSE}
dateRangeInput(inputId="dateRangeChoice",
              label="Please select dates:"
)
```


Date values:

```{r print-dates-input, echo=FALSE}
renderPrint(class(input$dateRangeChoice))
renderPrint(input$dateRangeChoice)
```


# Text Input

```{r text-input, echo=FALSE}
textInput(inputId="textSample", label="Space to enter text:")

textAreaInput(inputId="textAreaSample", label="Area to enter more text:")

passwordInput(inputId="passwordExample", label="Protext your password:")
```

Password value:

```{r print-text-input, echo=FALSE}
renderPrint(input$passwordExample)
renderText(input$passwordExample)
```


